[versions]
compose = "1.0.0-beta04"
kotest = "4.4.3"
ktlint = "0.41.0"

[libraries]
android-material = "com.google.android.material:material:1.3.0"
compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
activity-compose = "androidx.activity:activity-compose:1.3.0-alpha06"
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }