[versions]
compose-compiler = "1.4.6"
kotest = "5.6.2"
kotlin = "1.9.0"
ktlint = "0.48.2"

[libraries]
android-plugin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-plugin-gradle = "com.android.tools.build:gradle:8.0.2"
compose-foundation-foundation = "androidx.compose.foundation:foundation:1.4.3"
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }

[plugins]
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
spotless = { id = "com.diffplug.spotless", version = "6.19.0" }