[versions]
compose = "1.4.1"
kotest = "5.5.5"
ktlint = "0.48.2"

[libraries]
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }