[versions]
compose = "1.0.0-beta07"
kotest = "4.6.0"
ktlint = "0.41.0"

[libraries]
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }